### ISSUE TITLE
Benchmarks suggetions

### ISSUE THREAD

**Issue by oz123** [scottrogowski/mongita#1]
@scottrogowski, this is a really nice project. The name is awesome too!

I have not had the chance yet to really git it a spin, however I think the benchmarks can be improved a bit.
I believe SQLite performance comparision is can be improved if you compared insertion of a [dict into JSON. ](https://www.sqlite.org/json1.html)

I think this is where most of the CPU cycles in the row insertion are consumed, which make SQLite look so bad ...
```
def _to_sqlite_row(doc):
    doc['_id'] = str(doc['_id'])
    return (doc['_id'], doc['name'], doc['dt'], doc['count'], doc['city'],
            doc['content'], doc['percent'],
            json.dumps(doc['dict'], default=json_util.default))
```

Thanks for publishing this nifty little project!

**Comment by scottrogowski** [comment]
Thanks @oz123! Using sqlite's json type was actually my original approach but iirc, performance was worse - maybe for the finds? I'll try to modify and get confirmation that this was actually the case.

**Comment by scottrogowski** [comment]
I'm not sure what the problem was but I've added the SQLite (JSON1) to the benchmark list and it does appear to perform somewhat better than traditional SQLite. Thank you for pointing this out and don't hesitate if you think anything else can be improved.

**Comment by oz123** [comment]
Extremely nice of you! You already updated the graphs too!
Benchmarking is a tricky art...

**Comment by scottrogowski** [comment]
Nah. Nice of you. Thanks for digging into the code and pointing it out.
