### ISSUE TITLE
failed to import on python 3.6, no attribute `Pattern`

### ISSUE THREAD

**Issue by chrisbeardy** [scottrogowski/mongita#10]
Hi, I get the following error when trying to import mongita in python 3.6.

```bash
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from mongita import MongitaClientDisk
  File "/home/chris/GitWS/tinydb_sqlite/venv/lib/python3.6/site-packages/mongita/__init__.py", line 1, in <module>
    from . import collection
  File "/home/chris/GitWS/tinydb_sqlite/venv/lib/python3.6/site-packages/mongita/collection.py", line 39, in <module>
    re.Pattern: b'\n',
AttributeError: module 're' has no attribute 'Pattern'
```

Looks like 3.6 does not support  `Pattern`. Looks like other projects have the same issue https://github.com/getsentry/responses/pull/196/files, https://github.com/beetbox/beets/issues/2978

To continue to support 3.6 you may have to add something like:

![Screenshot from 2021-06-19 20-06-04](https://user-images.githubusercontent.com/20585410/122653045-f9d8ad00-d139-11eb-98e4-5f07a5284215.png)

in an appropriate place

**Comment by scottrogowski** [comment]
Hey @chrisbeardy thanks for the issue report. You're correct, this was an oversight on my part. Sorry about that.

I attempted to add changes to make Mongita 3.6 compatible but unfortunately, I found another incompatibility that would have taken significant work to address - if it could be addressed cleanly at all. Even then, I suspect there would have been more problems after that.

So, instead, I decided to bump the required Python version to 3.7+.

Sorry about that. Hope that it will be possible to work around this on your end.
