### ISSUE TITLE
Where are the databases / collections?

### ISSUE THREAD

**Issue by jabbalaci** [scottrogowski/mongita#13]
You should mention in the README where the databases / collections are stored physically. I had to use strace to figure out they are in `~/.mongita` under Linux.

Edit: how can we store the data in the current (project) directory (similarly to SQLite)?

**Comment by scottrogowski** [comment]
Hello,

I’m on holiday and not by a computer at the moment. By default, the database is stored in ~/.mongita. The first argument to MongitaClientDisk can specify a different directory. I can’t recall at the moment whether this is absolute or relative but there’s a related PR that I will get in shortly. 

Let me know if this answers your question

**Comment by scottrogowski** [comment]
I merged a PR to add info to the README. Closing...
