### ISSUE TITLE
Is this api thread safe at all?

### ISSUE THREAD

**Issue by shi-yan** [scottrogowski/mongita#14]
I'm experiencing weird issues, 

the api will throw a key error exception when accessing a dict. And after that, the db will be erased.

It seems to be a thread safety issue? read/write can't happen at the same time.

**Comment by shi-yan** [comment]
sorry, the problem seems to be on my side. closing

**Comment by scottrogowski** [comment]
That sounded bad! I'm glad you figured it out and please do let me know if anything else comes up. While thread safety is experimental, I'd like to address any issues that come up.
