### ISSUE TITLE
SQLite benchmark is fudged (no primary key index)

### ISSUE THREAD

**Issue by snej** [scottrogowski/mongita#2]
In the [SQLite schema](https://github.com/scottrogowski/mongita/blob/e1b3855b2b77782c25e102d7ba1745db76bc53cb/benchmark_tests/benchmark.py#L101) you forgot to declare `idd` a primary key, or even to add an index on it. Thus all of your `find_one()` calls have O(n) performance.

I'm struggling to believe that this was unintentional, especially since you did bother to add indexes on other columns. Surely when you saw the jaw-droppingly bad numbers for SQLite in "get 1000 docs by ID", you would have investigated?

**Comment by scottrogowski** [comment]
Please be civil. I don't often work in SQL so it was an oversight. Honestly, I couldn't figure out why SQLite would be so slow in that category. It is fixed now. Thank you for pointing it out.
