### ISSUE TITLE
Feature request: Allow callback functions in slow codepatch

### ISSUE THREAD

**Issue by Dobatymo** [scottrogowski/mongita#22]
Hi!

I am not sure if it's against the design goals of the library, but it would be very useful to be able to provide custom Python callback functions to the `_doc_matches_slow_filters` code path of the `find()` method. That means a custom function which takes a single document and returns `True` or `False` if it should be included in the output. As fast as I understand this should be easy to implement as that's what the non-indexed code path is basically doing anyway.

Using that it would also be easy to work around operators which are not implemented yet.

**Comment by scottrogowski** [comment]
Hey,

Sorry for the wait. This skipped my mind. 

It is against the design goals of the library which are to replicate - as close as possible - the interface of mongodb/pymongo. 

For find, what you are trying to do can be easily done outside the library and it will be the exact same speed. The _doc_matches_slow_filters call is what it sounds like - each document is accessed one-by-one to see if it’s a match. So doing ‘next(filter(func, client.db.coll.find({})))’ (e.g. using a cursor) will find the next document that matches your filter and won’t pull them all out at once. 

Let me know if I’m misunderstanding something or you don’t think this is a good solution. I’m open to being wrong

**Comment by Dobatymo** [comment]
> It is against the design goals of the library which are to replicate - as close as possible - the interface of mongodb/pymongo.
Yes that's what I thought.

>  So doing ‘next(filter(func, client.db.coll.find({})))’ (e.g. using a cursor) will find the next document that matches your filter and won’t pull them all out at once.

Yes it's actually enough to accomplish what I want to do. Only additional steps like sorting need to be added manually and cannot reuse the mongita pipeline. But it's not really a issue for me.

Thanks for your reply. I will close this.
