### ISSUE TITLE
Question about parallelization

### ISSUE THREAD

**Issue by PlatonB** [scottrogowski/mongita#27]
I see that it is written in the docs:

> It is not process-safe

But the particular case is not clear. What if to create **one** client to work with **one** collection?. [Example with MongoDB](https://github.com/PlatonB/high-perf-bio/blob/6b9a6d01371205314aa3f8604a7be226a4bf30d8/split.py#L279). Is it a safe approach?

**Comment by scottrogowski** [comment]
I don't think this will be safe. Even though you are creating a new client for every process, the problem is that it's accessing the same database and processes can overwrite each other. If you use ThreadPool instead of pool, it is probably safe but I don't want to guarantee that it's bug free yet.

**Comment by scottrogowski** [comment]
Process safety is something I intend to fix when I make the switch to a SQLite backend. But I'm also not sure when time will open up for me to work on that.
