### ISSUE TITLE
There are some wrong in README.md <Hello world>

### ISSUE THREAD

**Issue by zhongjimeiying** [scottrogowski/mongita#3]
**wrong**: `mongoose_types.insert_many([{'name': 'Meercat', 'not_into', 'Snakes'},{'name': 'Yellow mongoose': 'eats': 'Termites'}])`
**desc**: the argument is not a correct python dict

**wrong**: `list(coll.find({'weight': {'$gt': 1}))`
`coll.delete_one({'name': 'Meercat'})`
**desc**: the variable *coll* is not existed, should be *mongoose_types*

**Comment by scottrogowski** [comment]
Woops. Thank you. Will fix tomorrow.

**Comment by scottrogowski** [comment]
Fixed. Thanks again.
