### ISSUE TITLE
Connect to mongita db from other machine

### ISSUE THREAD

**Issue by cr-razvanzavate** [scottrogowski/mongita#31]
Hello, I was wondering if we can access a mongita db created on the disk of one machine on another machine. We have RPyC connection between those 2 machines if it helps. (We don't want to use an actual mongoDB because we can't install mongo on them). Thanks!

**Comment by scottrogowski** [comment]
Hi @cr-razvanzavate. Sorry for the delay in responding to you. For now, you can put a mongita database anywhere that maps to a local filesystem. You can see where the database file gets opened on this line https://github.com/scottrogowski/mongita/blob/master/mongita/engines/disk_engine.py#L52. I'm not familiar with RPyC so I can't say for sure there is no easy way to add this functionality but my sense is that this is the case.
