### ISSUE TITLE
Question about mongita memory

### ISSUE THREAD

**Issue by bossauh** [scottrogowski/mongita#32]
Would it be preferable to use mongita memory over redis for caching? The reason being that I'm already using mongodb as my main database and implementing mongita as a cache layer seems to be the easiest route. How's the performance of it compared to redis?

**Comment by scottrogowski** [comment]
Hi @bossauh. 

Mongita memory is a Python-level cache and Redis is in a separate process at best and over the network at worst. So, all things being equal, Mongita _should_ be faster than Redis. However, I would validate that by testing the speed yourself. If you care to share, I would be curious to see anything you come up with.
