### ISSUE TITLE
Are $and, $or queries supported?

### ISSUE THREAD

**Issue by ignacio-rh** [scottrogowski/mongita#33]
Hey Scott

First thanks a lot for the package; found it really useful. 

I'm having some issues anding together some search conditions. It looks like using $and fails. Example: 

`test = [{'name': 'foo'}, {'name':'bar'}]

db['assessment'].delete_many({})

db['assessment'].insert_many(test)

print(db['assessment'].count_documents({ 'name': { '$in' :['foo'] }}))

db['assessment'].count_documents({'$and':  [{ 'name' :'foo' }]})`

When im trying to find something in a collection 'assessment'

Any thoughts appreciated!

**Comment by scottrogowski** [comment]
Hi @ignacio-rh 

$and is not currently implemented. The list of everything implemented can be found on the README. You're welcome to contribute if you want to try a PR!
