### ISSUE TITLE
Pip install mongita -- Segment Fault

### ISSUE THREAD

**Issue by lwanger** [scottrogowski/mongita#7]
I am trying to install mongita on Python 3.9 on a Windows machine. I am getting the following error. Any ideas?:

$ pip install mongita
Collecting mongita
  Using cached mongita-1.0.0.tar.gz (33 kB)
    ERROR: Command errored out with exit status 3221225477:
     command: 'D:\anaconda\envs\py39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\len_w\\AppData\\Local\\Temp\\pip-install-ee8rj6s8\\mongita\\setup.py'"'"'; __file__='"'"'C:\\Users\\len_w\\AppData\\Local\\Temp\\pip-install-ee8rj6s8\\mongita\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn'
         cwd: C:\Users\len_w\AppData\Local\Temp\pip-install-ee8rj6s8\mongita\
    Complete output (11 lines):
    running egg_info
    creating C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info
    writing C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\PKG-INFO
    writing dependency_links to C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\dependency_links.txt
    writing requirements to C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\requires.txt
    writing top-level names to C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\top_level.txt
    writing manifest file 'C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'LICENSE,'
    writing manifest file 'C:\Users\len_w\AppData\Local\Temp\pip-pip-egg-info-m1bl3ksn\mongita.egg-info\SOURCES.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 3221225477: python setup.py egg_info Check the logs for full command output.

Segmentation fault

**Comment by lwanger** [comment]
BTW, it works if I pip install on Python 3.8

**Comment by scottrogowski** [comment]
Hi @lwanger. Sorry, I'm just seeing this now. I tried on my end and my install works on Python 3.9. I don't have a windows machine to try to reproduce.

My best guess is that this is a problem with setuptools and/or pip. Have you tried resolving through something like this? https://github.com/facebook/prophet/issues/418

**Comment by lwanger** [comment]
I tried to reproduce the error and pip install was working today on v3.9.
